server:
    port: 8096
spring:
    data:
        mongodb:
            # atlas 
            uri: "mongodb+srv://rommel:proyectobootcamp@bootcamp.9fgvk.mongodb.net/bootcamp?retryWrites=true&w=majority"
